# Generated by Django 4.1.3 on 2022-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_location_address_location_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_animal_in',
            field=models.IntegerField(choices=[(0, '불가'), (1, '가능'), (2, '정보 없음')], default=2),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='location',
            name='logitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
