# Generated by Django 4.1.3 on 2022-11-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='logitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
    ]
