# Generated by Django 4.1.3 on 2022-11-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_location_latitude_alter_location_logitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='on_off',
            field=models.IntegerField(choices=[(0, '음식점'), (1, '애견')], default=0),
        ),
    ]
