# Generated by Django 4.1.3 on 2022-11-30 04:28

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_location_on_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='profile',
            field=models.ImageField(max_length=255, null=True, upload_to=user.utils.rename_image),
        ),
    ]
