# Generated by Django 4.1.3 on 2022-12-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='profile',
            field=models.ImageField(max_length=255, null=True, upload_to='media/'),
        ),
    ]
