# Generated by Django 4.1.3 on 2022-12-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_category_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='profile',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/'),
        ),
    ]
