# Generated by Django 4.1.3 on 2022-11-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', '남자'), ('f', '여자')], default='m', max_length=1),
        ),
    ]
