# Generated by Django 4.1.3 on 2022-11-14 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_contents_alter_category_name'),
        ('user', '0003_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='main.category'),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(null=True, upload_to='media/')),
                ('name', models.CharField(max_length=20)),
                ('kind', models.IntegerField(choices=[(0, '강아지'), (1, '고양이'), (2, '어류'), (3, '조류'), (4, '파충류'), (5, '소동물'), (6, '기타')])),
                ('breed', models.CharField(max_length=20)),
                ('adoption_day', models.DateField()),
                ('birthday', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
