# Generated by Django 4.1.3 on 2022-12-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_location_lot_address'),
        ('user', '0003_alter_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='users', to='main.location'),
        ),
    ]
