# Generated by Django 4.1.3 on 2022-11-20 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_location'),
        ('user', '0004_alter_user_category_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='profile',
            field=models.ImageField(max_length=255, null=True, upload_to=user.utils.rename_image),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='main.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
