# Generated by Django 4.1.3 on 2022-11-21 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_location_latitude_alter_location_logitude'),
        ('user', '0005_alter_pet_profile_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='main.location'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
