# Generated by Django 4.1.3 on 2022-11-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='on_off',
            field=models.IntegerField(choices=[(0, '음식점'), (1, '애견')], default=0),
        ),
    ]
