# Generated by Django 4.1.3 on 2022-12-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_email_alter_user_on_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='on_off',
            field=models.IntegerField(choices=[(0, '음식점'), (1, '전체')], default=0),
        ),
    ]
